### ISSUE TITLE
Documentation Update/Note

### ISSUE THREAD

**Issue by iamrobert** [CodyHouse/cd-smooth-scrolling-changelog#1]
If you use your lazy-loading component for images - then native html smooth scroll fails to scroll to the correct place as it can't locate the correct scroll height. It seems to be an issue across the board.

So remove this:

```html {
scroll-behavior: smooth;
}
```

Change this:

`if( smoothScrollLinks.length > 0 && !Util.cssSupports('scroll-behavior', 'smooth') && window.requestAnimationFrame) {`

to this:
	
`if( smoothScrollLinks.length > 0 && window.requestAnimationFrame) {`

seems to work.

**Comment by claudia-romano** [comment]
Hi there, by default the smooth scrolling component uses the native CSS `scroll-behavior` property; the JS fallback is used only for browsers not supporting the `scroll-behavior` property.

With your changes, you are always using the JS fallback (even when `scroll-behavior` is supported) which we would like to avoid. 

When using the lazy loading component, the images are not loaded until they are in the viewport (which creates the scrolling issue). But you can use an image placeholder that has the same size of the final image, which will fix the issue. You can find more info about setting up a placeholder here:
https://codyhouse.co/ds/components/info/lazy-load

I'm going to close this issue as we won't include this solution on our documentation, but if you have any additional questions feel free to reopen it. 

Cheers!
